<?php

function hello_menu(){

    $items = array();

    $items['hello/hello_world'] = array(
        'title' => 'Hello world test' ,
        'page callback' => 'say_hello_world',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );

    return $items;
}

function say_hello_world(){
    $vars = array();
    $vars['type'] = "ul";
    $vars['title'] = "";
    $vars['attributes'] = array("");
    $vars['items'][0] = "this is a simple proof of concept module";

    return theme_item_list($vars);
}

