<?php
function mymodule_permission()
{
    return array(
        'edit my settings' => array(
            'title' => t('Edit My Settings'),
            'description' => t('Edit My Custom Settings Page'),
        ),
    );
}

function mymodule_menu()
{
    $result = array();
    $result['manage/mysettings'] = array(
        'title' => 'My Settings', // Title of our page
        'description' => 'My Custom Settings', // Description of our page
        'page callback' => 'drupal_get_form',
        'page arguments' => array('mymodule_form'), // function that will returns the results to our page
        'access arguments' => array('edit my settings'), // permission to access this page
        'type' => MENU_NORMAL_ITEM, // type of menu item
    );

    return $result;
}


function mymodule_form()
{

    $form = array();
    $form['mymodule_my_name'] = array(
        '#type' => 'textfield',
        '#title' => t('My Name'),
        '#default_value' => variable_get('mymodule_my_name', ''),
        '#required' => TRUE,
    );
    $form['mymodule_about_me'] = array(
        '#type' => 'textarea',
        '#title' => t('About Me'),
        '#default_value' => variable_get('mymodule_about_me', ''),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    $form['#submit'][] = 'system_settings_form_submit';
    return $form;
}


function mymodule_block_info()
{
    $blocks['mymodule_about_me'] = array(
        'info' => t('About Me'),
    );
    return $blocks;
}


function mymodule_block_view($delta = '')
{
    $block = array();
    switch ($delta) {
        case 'mymodule_about_me':
            $block['subject'] = variable_get('mymodule_my_title', ''); // set the subject of the block to our mymodule_my_title variable
            $block['content'] = variable_get('mymodule_about_me', ''); // set the content of the block to our mymodule_about_me variable
            break;
    }
    return $block;
}